import { useEffect, useMemo, useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { PageHeader } from '../../components/common/PageHeader';
import { Card, Button, Avatar } from '../../components/ui';
import { CLASS_OPTIONS, APP_NAME } from '../../constants';
import { notify } from '../../utils/notify';
import api from '../../api/api';

const STATUSES=['present','absent','late','leave'];
const colors={present:'text-green-700 bg-green-50',absent:'text-red-700 bg-red-50',late:'text-orange-700 bg-orange-50',leave:'text-slate-700 bg-slate-50'};
export default function AttendancePage(){
 const [students,setStudents]=useState([]),[attendance,setAttendance]=useState({}),[cls,setCls]=useState(CLASS_OPTIONS[0]?.value||''),[section,setSection]=useState('A'),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const [s,a]=await Promise.all([api.get('/students',{params:{class:CLASS_OPTIONS.find(x=>x.value===cls)?.label||cls,section,limit:500}}),api.get('/attendance',{params:{class:CLASS_OPTIONS.find(x=>x.value===cls)?.label||cls,section,from:date,to:date,limit:500}})]);const list=s.data.data||[];setStudents(list);const map={};list.forEach(x=>map[x._id]= 'present');(a.data.data||[]).forEach(x=>{map[x.student?._id||x.student]=x.status});setAttendance(map)}catch(e){notify.error(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[cls,section,date]);
 const counts=useMemo(()=>Object.fromEntries(STATUSES.map(s=>[s,students.filter(x=>attendance[x._id]===s).length])),[students,attendance]);
 const save=async()=>{setSaving(true);try{await api.post('/attendance/mark',{class:CLASS_OPTIONS.find(x=>x.value===cls)?.label||cls,section,date,records:students.map(s=>({student:s._id,status:attendance[s._id]||'present'}))});notify.success('Attendance saved successfully');await load()}catch(e){notify.error(e.message)}finally{setSaving(false)}};
 return <><Helmet><title>Attendance — {APP_NAME}</title></Helmet><PageHeader title="Attendance" subtitle="Mark and save daily student attendance" actions={<Button loading={saving} onClick={save}>Save Attendance</Button>}/><Card className="mb-5"><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div><label className="form-label">Class</label><select className="form-input" value={cls} onChange={e=>setCls(e.target.value)}>{CLASS_OPTIONS.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></div><div><label className="form-label">Section</label><input className="form-input" value={section} onChange={e=>setSection(e.target.value.toUpperCase())}/></div><div><label className="form-label">Date</label><input type="date" className="form-input" value={date} onChange={e=>setDate(e.target.value)}/></div></div><div className="flex flex-wrap gap-2 mt-4">{STATUSES.map(s=><span key={s} className={`badge ${colors[s]}`}><b>{counts[s]||0}</b> {s}</span>)}<Button size="sm" variant="success" onClick={()=>setAttendance(Object.fromEntries(students.map(s=>[s._id,'present'])))}>All Present</Button><Button size="sm" variant="outline" onClick={()=>setAttendance(Object.fromEntries(students.map(s=>[s._id,'absent'])))}>All Absent</Button></div></Card><Card padding={false} className="overflow-hidden"><div className="overflow-x-auto">{loading?<p className="p-8 text-center text-erp-muted">Loading students...</p>:<table className="erp-table min-w-[700px]"><thead><tr><th>#</th><th>Student</th><th>Roll No</th><th>Section</th><th>Status</th></tr></thead><tbody>{students.map((s,i)=><tr key={s._id}><td>{i+1}</td><td><div className="flex items-center gap-2"><Avatar src={s.user?.avatar} name={s.user?.name} size="sm"/><span>{s.user?.name}</span></div></td><td>{s.rollNo}</td><td>{s.section}</td><td><select className="form-input py-1 w-32" value={attendance[s._id]||'present'} onChange={e=>setAttendance(v=>({...v,[s._id]:e.target.value}))}>{STATUSES.map(x=><option key={x}>{x}</option>)}</select></td></tr>)}{!students.length&&<tr><td colSpan="5" className="text-center py-8 text-erp-muted">No students found for this class and section.</td></tr>}</tbody></table>}</div></Card></>;
}
